### ISSUE TITLE
gTile does not work on Debian 10 (gnome-shell 3.30)

### ISSUE THREAD

**Issue by gregorydlogan** [gTile/gTile#175]
I was previously seeing #162 as described in the original post, however uninstalling, rebooting, and reinstalling allowed gTile to show up again.  It does not, however, work.  I can get the settings menu to open, but hitting the accelerator keys gives me this in the debug log:

```
Nov 21 09:28:41 UX310UA gnome-shell[12297]: JS ERROR: TypeError: this.actor.ease is not a function
                                            show@/home/greg/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:1825:13                                                                                  
                                            showTiling@/home/greg/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:937:13                                                                             
                                            toggleTiling@/home/greg/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:964:9                                                                            
                                            show-toggle-tiling-alt@/home/greg/.local/share/gnome-shell/extensions/gTile@vibou/extension.js:410:45
```

I'm running Debian 10, with the default gnome-shell:
```
ii  gnome-shell                                                 3.30.2-11~deb10u2                            amd64        graphical shell for the GNOME desktop                                                   
ii  gnome-shell-common                                          3.30.2-11~deb10u2                            all          common files for the GNOME graphical shell                                              
ii  gnome-shell-extensions                                      3.30.1-1                                     all          Extensions to extend functionality of GNOME Shell
```

Everything was working great until an update a few weeks ago, although I can't give you a solid date.

**Comment by scherepanov** [comment]
Yes, it is a problem.
Looks like it is very hard to keep gTile compatible with older version of gnome-shell, they are forcing changes all the time.
I can suggest you go back to v 35, downloadable from EGO. That should work.

**Comment by gregorydlogan** [comment]
Sounds good, thanks for thr pointer!

**Comment by stoobie** [comment]
> I can suggest you go back to v 35, downloadable from EGO. That should work.
@scherepanov Can you please give more details (like a URL)? I'm having a similar problem on RHEL 8, Gnome 3.32.2.
